dist: trusty
sudo: false
language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
cache: pip
before_install:
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then if_lxml=:; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then if_pygments=:; fi
install:
- $if_lxml pip install lxml
- pip install pydiatra pyflakes
- $if_pygments pip install restructuredtext-lint pygments
script:
- $if_lxml ./sourceforge-authors jakub-wilk '(no author)'
- python3 -m pydiatra .
- python3 -m pyflakes .
- $if_pygments restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
