#!/usr/bin/env python3

# Copyright © 2017-2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import io
import json
import urllib.parse
import urllib.request

headers = {
    'User-Agent': 'sourceforge-authors (https://github.com/jwilk/sourceforge-authors)',
}

url_template = 'https://sourceforge.net/rest/u/{0}/profile'

authors_template = '{orig_user} = {name} <{user}@users.sourceforge.net>'

def get_user_name(user):
    url = url_template.format(urllib.parse.quote(user))
    request = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(request) as fp:
            with io.TextIOWrapper(fp, encoding='UTF-8') as tfp:
                data = json.load(tfp)
    except urllib.error.URLError as exc:
        if exc.code == 404:
            return
    return data['name']

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('users', metavar='USER', nargs='+')
    options = ap.parse_args()
    for user in options.users:
        orig_user = user
        if user in {'root', '(no author)'}:
            user = 'nobody'
            name = 'nobody'
        else:
            name = get_user_name(user) or '?'
        line = authors_template.format(
            orig_user=orig_user,
            user=user,
            name=name
        )
        print(line)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
